version: 1.0.{build}
os: Visual Studio 2015 RC
init:
  - ps: dnvm upgrade
environment:
  VisualStudioVersion: 14.0
install:
  - dnu restore
test_script:
  - ps: dnx test\Nine.Graphics.Test test
deploy:
- provider: NuGet
  api_key:
    secure: /Aez/maYDiX55BgGX9EkbhXBaBySsfdKifgB9SZxqySOrwtMVgPf7jOwS2XwKYJR
  on:
    branch: master