configuration: Release
os: Visual Studio 2015 RC
clone_depth: 1
environment:
  VisualStudioVersion: 14.0
  DNX_FEED: https://www.nuget.org/api/v2 
install:
  - git submodule -q update --init
  - dnvm install 1.0.0-rc1-update1
  - dnu pack src\Nine.Graphics --configuration Release --out artifacts
  - dnx -p test\Nine.Graphics.Test test
artifacts:
  - path: artifacts\*.nupkg
